theme: jekyll-theme-slate
title: "Experto en ciberseguridad y DevSecOps: desarrolle, ponga a prueba e implemente aplicaciones seguras"
description: "Conviértase en especialista en ciberseguridad y DevSecOps: comprenda los riesgos de una aplicación para priorizar las pruebas y correcciones; realice un Pentest"
url: "https://www.ilaria-academy.com/nextjob/appsec-cybersecurity-hacker/es/"
show_downloads: false
